language: python

os:
    - linux


cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"


matrix:
    fast_finish: true


install:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt


# command to run tests
script:
    - pytest --cov --mypy
after_success: coveralls
