"""empty message

Revision ID: 18dc73cc2b47
Revises: 
Create Date: 2020-04-23 14:00:18.241313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dc73cc2b47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_table('permission_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_groups'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('session_id', name=op.f('uq_sessions_session_id'))
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_authorised', sa.Boolean(), nullable=True),
    sa.Column('is_icu_trained', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('department_skill_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('start_day', sa.Integer(), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=True),
    sa.Column('constraint_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_skill_constraints_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_department_skill_constraints_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_skill_constraints'))
    )
    with op.batch_alter_table('department_skill_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_skill_constraints_skill_id'), ['skill_id'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_staff_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_department_id'), ['department_id'], unique=False)

    op.create_table('user_departments',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_user_departments_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_departments_user_id_users'), ondelete='CASCADE')
    )
    with op.batch_alter_table('user_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_departments_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_departments_user_id'), ['user_id'], unique=False)

    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission_groups.id'], name=op.f('fk_user_permissions_permission_id_permission_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permissions_user_id_users'), ondelete='CASCADE')
    )
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('staff_shift_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('min_start_hour', sa.Integer(), nullable=True),
    sa.Column('min_shift_hours', sa.Integer(), nullable=True),
    sa.Column('max_start_hour', sa.Integer(), nullable=True),
    sa.Column('min_shift_gap', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_staff_shift_constraints_staff_id_staff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_shift_constraints'))
    )
    with op.batch_alter_table('staff_shift_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_shift_constraints_staff_id'), ['staff_id'], unique=False)

    op.create_table('staff_skills',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_staff_skills_skill_id_skills')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_staff_skills_staff_id_staff')),
    sa.PrimaryKeyConstraint('staff_id', 'skill_id', name=op.f('pk_staff_skills'))
    )
    op.create_table('weekly_max_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_weekly_max_hours_staff_id_staff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_max_hours'))
    )
    with op.batch_alter_table('weekly_max_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_max_hours_staff_id'), ['staff_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_max_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_max_hours_staff_id'))

    op.drop_table('weekly_max_hours')
    op.drop_table('staff_skills')
    with op.batch_alter_table('staff_shift_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_shift_constraints_staff_id'))

    op.drop_table('staff_shift_constraints')
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_permissions_permission_id'))

    op.drop_table('user_permissions')
    with op.batch_alter_table('user_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_departments_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_departments_department_id'))

    op.drop_table('user_departments')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_department_id'))

    op.drop_table('staff')
    with op.batch_alter_table('department_skill_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_skill_constraints_skill_id'))

    op.drop_table('department_skill_constraints')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('sessions')
    op.drop_table('permission_groups')
    op.drop_table('departments')
    # ### end Alembic commands ###
