"""empty message

Revision ID: 818444726152
Revises: 18dc73cc2b47
Create Date: 2020-04-23 14:21:56.843251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818444726152'
down_revision = '18dc73cc2b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reserve', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('is_reserve')

    # ### end Alembic commands ###
